### ISSUE TITLE
As an invitee, I want to respond to a poll

### ISSUE THREAD

**Issue by sohilpandya** [DRDD2016/app#100]

**Comment by sohilpandya** [comment]
Relates to epic #17 
- [ ] Click on feed item to go to poll view
- [ ] Ability to vote on poll questions
⚠️  User can only have one vote per category

**Comment by sohilpandya** [comment]
@rickardinho @Dameodeare just want to confirm that the above is true, i.e. you can only choose **one** option per poll category.

e.g.
Where 1 - Harrods
Where 2 - McDonald's

The user couldn't choose both, they'd have to select one.

Please let us know here.

**Comment by rickardinho** [comment]
Hi @sohilpandya & @minaorangina,
cc: @Dameodeare,

False. In the design we said that people could vote for 1, 2 or all 3 (with all votes counted as 1).
For example, if you're voting on Friday, Saturday or Sunday and you were available for all 3, you could vote for all 3.
Likewise, if you were happy with Harrods and McDonald's, then you could vote for both.  This works better for the host who can see how many people are agreeable before confirming the event.
Otherwise indifferent people could swing the vote if they could only vote for 1 option.

The votes can be toggled on/off, so that if somebody changes their mind, they can toggle them again.  Example, I vote for both Harrod's and McDonald's, but when I do a bit more research, I find that I'm unimpressed with McDonald's vegan options, so I toggle my vote for McD's to off.  

Dave

**Comment by minaorangina** [comment]
@rickardinho Ok, thanks for clearing that up.
