### ISSUE TITLE
User should be able to delete an event they are hosting

### ISSUE THREAD

**Issue by sohilpandya** [DRDD2016/app#168]

**Comment by minaorangina** [comment]
I've realised there's a bug: deleted events aren't being deleted from the calendar.  When you try to navigate to calendar, the app breaks.  Could you add that change?  Also, could you write a test to make sure the respective calendar item gets deleted in the database?

**Comment by sohilpandya** [comment]
@minaorangina didn't know that needed to be deleted, will look into it.

**Comment by sohilpandya** [comment]
@minaorangina could you please give me a brief description of how/when the calendar lists are being created, saved and viewed.

I've had a quick look but just need to understand the whole flow.

It's not that straight forward, I'll have to run a function very similar to add event to calendar but instead of pushing, I'll have to remove that particular event from the users calendar list. please let me know if I've thought that incorrectly. 

:)

**Comment by minaorangina** [comment]
@sohilpandya The calendar is populated anytime a `ConfirmedEvent` is created.  This could be on the initial create event screen, or after a host converts a poll into a `ConfirmedEvent`.

This only happens in one place, in the `NotifyEveryone` function.

Calendar is viewed when you navigate to `/calendar`.

So currently, whenever a change to an event is made, `NotifyEveryone` runs, in order to inform all the relevant parties that something's changed.  `NotifyEveryone` works on the assumption that the given event exists.  

If an event is deleted, it won't exist at the point of creating a notification - if you look at the signature of the functions that execute inside of `NotifyEveryone`, they all need an eventID, or the event object itself, which obviously won't exist.  This is fine, it just means that the relevant notification will need to be created **before** the event is actually deleted. 

The notification will also probably need a flag like `isCancelled (true/false)`, so that we can distinguish a cancellation notification from the other ones back in the Notification component.

Finally, we'd need to update our tests to account for all this.  So something that tests the notification looks the way we expect when an event is deleted, and that the relevant things no longer exists in the database, i.e. the event itself and any references to it in users' notifications and calendars.

Does this make sense?

**Comment by sohilpandya** [comment]
- [ ] convert calendar list to a set
- [ ] create function that will remove the deleted event from the above set for al the users.
