### ISSUE TITLE
name of invitee not displaying next to icon

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#382]
odd example where name doesn't align correctly next to icon.

![image1](https://cloud.githubusercontent.com/assets/17908724/16507022/88e8cde4-3f1e-11e6-9c3b-da1389bd5e69.PNG)

**Comment by minaorangina** [comment]
@rickardinho it's because there's not quite enough space in the column for the name to fit (the same happens for my name).
This is a constraint of the page's design: with this layout it's bound to happen sometimes. 

At this point your options are to either make the font and/or image smaller, or to stack the going/maybe/not going sections on top of each other, rather than have them side by side

**Comment by rickardinho** [comment]
Could we just make the font slightly smaller, possibly one or two pts less. Leave the picture as it is.

**Comment by rickardinho** [comment]
Could we also move the Not responded title and people below the going, maybe not goings. I think you want to see these first before the not respondeds.

**Comment by sohilpandya** [comment]
@rickardinho can you please test.

Thanks
